# Ejercicio 🏡

## 📍 Objetivo
<br>Realizar la preparación de datos de la Encuesta anual de hogares realizada en todo el territorio de la Ciudad de Buenos Aires, Argentina en el 2019.
<br>Prácticamente vas a acondicionar el dataset para que te quede listo para buscar correlaciones o entrenar algún modelo de Machine Learning.

El dataset proviene del Open Data del Gobierno de Buenos Aires: [Encuesta anual de hogares 2019](https://data.buenosaires.gob.ar/dataset/encuesta-anual-hogares)

---
## 📍 Consigna 1
**_1) Cargamos los datos_**
- Carguen el dataset:
```
  data = pd.read_csv("encuesta-anual-hogares-2019.csv", sep=',')
```
**_2) Inspección inicial_**
- Eliminen las columnas `id` y `hijos_nacidos_vivos`

**_3) Discretización_**
- Para las siguientes columnas discreticen por igual frecuencia e igual rango.
    <br>`ingresos_familiares` con q=8
    <br>`ingreso_per_capita_familiar` con q=10

- En algunas situaciones hay ciertos elementos que se repiten al momento de discretizar, una forma de eliminar duplicados es con el argumento `duplicates='drop'`.
    <br><br>Para las siguientes columnas `ingreso_total_lab` y `ingreso_total_no_lab` consideren:
    ```
    data['ingreso_total_lab'] = pd.qcut(data['ingreso_total_lab'], q=10, duplicates='drop')
    data['ingreso_total_no_lab'] = pd.qcut(data['ingreso_total_no_lab'], q=4, duplicates='drop')
    ```

- Para la columna `edad` discreticen usando igual distancia con `bins=5`.

**_4) Preparación de datos_**
- Cambien el tipo de dato a `str` de las siguientes columnas: `comuna` y `nhogar`.
  <br>_¿Por qué hacemos esto?_ Para estas columnas el número es simplemente una connotación, para representar una comuna por ejemplo pero no hay una relación numérica entre ellos.

- _¿Qué esperas como valor en la columna `años_escolaridad`?_ Número enteros pero no siempre es así, cada entidad o empresa tiene diferentes formas de rellenar una encuesta.
    <br>Evalua lo siguiente: `data['años_escolaridad'].unique()`, vas a poder ver los valores únicos en la columna. Donde destacamos que todos son `object/string`.

- Reemplazar `Ningun año de escolaridad aprobado` por un '0'.
<br>Efectivamente por '0' y no 0, porque esta columna maneja datos tipo `object/string`.
    ```
    data['años_escolaridad'] = data['años_escolaridad'].replace('Ningun año de escolaridad aprobado', '0')
    ```

- Vamos a convertir los tipos de datos de la columna anterior `años_escolaridad` a enteros.
    <br>De manera intuitiva podríamos hacer:
    ```
    data['años_escolaridad'] = data['años_escolaridad'].astype("Int32")
    ```
    PEROOOOOOO marca un error, ¿cierto?
    
    Posiblemente muchas veces les pase que cuando hagan una _cast_ (conversión de un tipo de dato a otro) pueden llegar a tener conflictos si esa columna tienen _NaN_. Para este caso si queremos convertir los valores de la columna `años_escolaridad` de _string_ a _int_, hay que hacer un paso intermedio que es pasarlo a _float_.
    ```
    data['años_escolaridad'] = data['años_escolaridad'].astype(float).astype("Int32")
    ```

- Discreticen para la columna `años_escolaridad` por igual frecuencia e igual rango con un `q=5`

- No necesariamente siempre hay que rellenar los `NaN` en todas las columnas, porque quizás esa cantidad de `NaN` no es tan representativa para nuestro análisis. Así que podes eliminarlo para todo el dataframe o para ciertas columnas.
    ```
    # Eliminar filas que contengan NaN
    data = data.dropna(subset=['situacion_conyugal', 'sector_educativo', 'lugar_nacimiento', 'afiliacion_salud'])
    ```
- Después de eliminar filas, podes resetear el índice para que mantenga la secuencia:
    ```
    data = data.reset_index(drop=True)
    ```

- Rellenar los datos faltantes para la columna `años_escolaridad`. Primero añadan la categoría `desconocido` y luego hacen un rellenado de los datos faltantes con `desconocido`.

- Rellenar los datos faltantes para la columna `nivel_max_educativo` con `value=desconocido`

## 1) Cargamos los datos

In [ ]:
!pip install funpymodeling

Requirement already satisfied: funpymodeling in /usr/local/lib/python3.12/dist-packages (0.1.9)
Requirement already satisfied: flake8<7.0.0,>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (6.1.0)
Requirement already satisfied: jupyter<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (1.1.1)
Requirement already satisfied: matplotlib<4.0.0,>=3.7.1 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (3.10.0)
Requirement already satisfied: numpy<2.0.0,>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.1.4 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (2.2.2)
Requirement already satisfied: pre-commit<4.0.0,>=3.3.2 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (3.8.0)
Requirement already satisfied: pytest<8.0.0,>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (7.4.4)
Requirement already satisfied: scikit-learn<2.0.0,>=1.2.2 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (1.6.1)
Requirement already satisfied: seaborn<0.13.0,>=0.12.2 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (0.12.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.6.3 in /usr/local/lib/python3.12/dist-packages (from funpymodeling) (4.15.0)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (0.7.0)
Requirement already satisfied: pycodestyle<2.12.0,>=2.11.0 in /usr/local/lib/python3.12/dist-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (2.11.1)
Requirement already satisfied: pyflakes<3.2.0,>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from flake8<7.0.0,>=6.0.0->funpymodeling) (3.1.0)
Requirement already satisfied: notebook in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (6.5.7)
Requirement already satisfied: jupyter-console in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (6.6.3)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (7.16.6)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (6.17.1)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (7.7.1)
Requirement already satisfied: jupyterlab in /usr/local/lib/python3.12/dist-packages (from jupyter<2.0.0,>=1.0.0->funpymodeling) (4.4.7)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (25.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.7.1->funpymodeling) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.4->funpymodeling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.4->funpymodeling) (2025.2)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (3.4.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (2.6.14)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (6.0.2)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit<4.0.0,>=3.3.2->funpymodeling) (20.34.0)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.12/dist-packages (from pytest<8.0.0,>=7.3.1->funpymodeling) (2.1.0)
Requirement already satisfied: pluggy<2.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from pytest<8.0.0,>=7.3.1->funpymodeling) (1.6.0)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (1.16.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.2.2->funpymodeling) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<4.0.0,>=3.7.1->funpymodeling) (1.17.0)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (0.4.0)
Requirement already satisfied: filelock<4,>=3.12.2 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (3.19.1)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit<4.0.0,>=3.3.2->funpymodeling) (4.4.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.15)
Requirement already satisfied: ipython>=7.23.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (7.34.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (7.4.9)
Requirement already satisfied: matplotlib-inline>=0.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.1.7)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (6.4.2)
Requirement already satisfied: traitlets>=5.1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.7.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.15)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.8.1)
Requirement already satisfied: prompt-toolkit>=3.0.30 in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.19.2)
Requirement already satisfied: async-lru>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.14.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (75.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (6.2.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.2)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (5.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.5.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (25.1.0)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.22.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.3.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.4.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.10.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2025.8.3)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.16.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.9.0)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.4)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.5.3)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.8.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (25.1.0)
Requirement already satisfied: babel>=2.10 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.12.1)
Requirement already satisfied: jsonschema>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (4.25.1)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.32.4)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat>=5.7->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.21.2)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.2.13)
Requirement already satisfied: ptyprocess in /usr/local/lib/python3.12/dist-packages (from terminado>=0.8.3->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.7.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.8)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.25.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.3.1)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.8.5)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.27.1)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.3.0)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (0.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.5.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook->jupyter<2.0.0,>=1.0.0->funpymodeling) (2.23)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter<2.0.0,>=1.0.0->funpymodeling) (3.0.0)

In [ ]:
import pandas as pd
from funpymodeling.exploratory import freq_tbl, status

In [ ]:
!pip install -U gdown

# Descargar todo el contenido de la carpeta compartida
!gdown --folder "https://drive.google.com/drive/folders/1gARv-63rYN3_IcpYj0hfAjVUKcW5TVFE"

Requirement already satisfied: gdown in /usr/local/lib/python3.12/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from gdown) (3.19.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.12/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from gdown) (4.67.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (2.8)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (2025.8.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown) (1.7.1)
Retrieving folder contents
Retrieving folder 1K7JuYXxRv4TxxwEjIiXZUaEqRQgnKxbq tp1
Retrieving folder 1CQXY1UzAPZk24NWbBJhVIXYr04RVzM6s tp2
Processing file 1j84XJDRHmWuJL_PQmLk0Wk5vsRA7KEr4 heart_2020_cleaned.csv
Processing file 1VgGPlBVq0G5PbwDYNZovZLQ_cAmJ-sg6 HeartAttackedPredictor.ipynb
Retrieving folder 1lwgSKaDYTTjEckryWamiV0nz4Mk341Ee tp3
Processing file 1OCN2u8yY3Nur_JPrhH_F2cRFEh_E_r-1 HR_Analytics.csv
Processing file 1-AJpc0DFAA7PU5Qk3VUoKRHd_B4YxD4h HR_Analytics.ipynb
Processing file 1IJs5ApmWoW7PDqbHkTHU1nuGcRBmGE6p HR-Employee-Attrition.csv
Processing file 1xYnJ12rHDfc2Ow2Kji-cVduixK3ge9zq stroke_healthcare.ipynb
Retrieving folder 1zb4D_n8JAI2KgLTC6iXe_gLtStqsbwFv tp4
Retrieving folder 1IIustiRbClCrNnm0N9y88N8tQzGKCxz6 Actividad_jueves
Processing file 1IWVNIVT1feXTfBDq2S9CdWeIrGN7AUj1 encuesta-anual-hogares-2019.csv
Processing file 1rJcEV0YP-nTRmxziBB9417F-dIKdFCl2 new_data.csv
Processing file 1awmNUczRXpLfy4SVv0WcB-6T1dBukxBy Preprocesamiento.ipynb
Processing file 1feoFoMUws9Rqq5LwBCFZ6AwZxBSrfBqi tarea_respuesta1.csv
Processing file 1-iMiShMrd2e9u_4xHFEqSHNgJevW8GEz tarea_respuesta2.csv
Retrieving folder 1qQyOKb21hWSPKaRc8e8OMsEJOKJ63G8Q Archivos_del_martes
Processing file 13ftF-0HLW4FNKJN29t2Dqpg7J_rGTue- bank_marketing.ipynb
Processing file 10K-o2kY9j6kt2X8-TT4tbKtSuZrYGd7s bank-additional-full.csv
Processing file 1pnuFvs5E2aLB_xDLg9jxlHn8a-xnIpU3 categories_ohe.pickle
Processing file 159gW5RPsN_PYfrJZjtw3qo32WNwyQauI limpieza_datos_nulos.pickle
Processing file 1NSJ0KFhOtjMTE0WHjlSlwVB-_EIZcDB2 tarea_respuesta1.csv
Processing file 1rFPxoS4mTjn0zWa0oleGLzhd_KUwWqSN tarea_respuesta2.csv
Processing file 17AFvwGkPL7midocDg40OIP-ZVt1Hjsek 2/9.ipynb
Processing file 1K_4B0oQIDThK4U2rUUoDCPXGqzEKTUZz archive.zip
Processing file 18TvelehEBbcPf9qP69QAdrr8mLcwIBlK dataset_phishing.csv
Processing file 1AqNP3cV9Hzn0JaB9xMh8C68LXgXwUbmg IntroPhyton.ipynb
Processing file 1d_HHaVCs0gn0Oiyn9_CKJQEMwNtJ3Noo Phishing_Legitimate_full.csv
Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1j84XJDRHmWuJL_PQmLk0Wk5vsRA7KEr4
To: /content/Bootcamp Data Science-Grupo 1/tp2/heart_2020_cleaned.csv
100% 25.2M/25.2M [00:00<00:00, 66.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VgGPlBVq0G5PbwDYNZovZLQ_cAmJ-sg6
To: /content/Bootcamp Data Science-Grupo 1/tp2/HeartAttackedPredictor.ipynb
100% 235k/235k [00:00<00:00, 85.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1OCN2u8yY3Nur_JPrhH_F2cRFEh_E_r-1
To: /content/Bootcamp Data Science-Grupo 1/tp3/HR_Analytics.csv
100% 259k/259k [00:00<00:00, 109MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-AJpc0DFAA7PU5Qk3VUoKRHd_B4YxD4h
To: /content/Bootcamp Data Science-Grupo 1/tp3/HR_Analytics.ipynb
100% 1.91M/1.91M [00:00<00:00, 162MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IJs5ApmWoW7PDqbHkTHU1nuGcRBmGE6p
To: /content/Bootcamp Data Science-Grupo 1/tp3/HR-Employee-Attrition.csv
100% 228k/228k [00:00<00:00, 86.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1xYnJ12rHDfc2Ow2Kji-cVduixK3ge9zq
To: /content/Bootcamp Data Science-Grupo 1/tp3/stroke_healthcare.ipynb
100% 2.32M/2.32M [00:00<00:00, 120MB/s]
Downloading...
From: https://drive.google.com/uc?id=1IWVNIVT1feXTfBDq2S9CdWeIrGN7AUj1
To: /content/Bootcamp Data Science-Grupo 1/tp4/Actividad_jueves/encuesta-anual-hogares-2019.csv
100% 5.17M/5.17M [00:00<00:00, 67.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1rJcEV0YP-nTRmxziBB9417F-dIKdFCl2
To: /content/Bootcamp Data Science-Grupo 1/tp4/Actividad_jueves/new_data.csv
100% 2.57k/2.57k [00:00<00:00, 8.02MB/s]
Downloading...
From: https://drive.google.com/uc?id=1awmNUczRXpLfy4SVv0WcB-6T1dBukxBy
To: /content/Bootcamp Data Science-Grupo 1/tp4/Actividad_jueves/Preprocesamiento.ipynb
100% 43.5k/43.5k [00:00<00:00, 57.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1feoFoMUws9Rqq5LwBCFZ6AwZxBSrfBqi
To: /content/Bootcamp Data Science-Grupo 1/tp4/Actividad_jueves/tarea_respuesta1.csv
100% 1.21k/1.21k [00:00<00:00, 5.37MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-iMiShMrd2e9u_4xHFEqSHNgJevW8GEz
To: /content/Bootcamp Data Science-Grupo 1/tp4/Actividad_jueves/tarea_respuesta2.csv
100% 8.75k/8.75k [00:00<00:00, 32.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=13ftF-0HLW4FNKJN29t2Dqpg7J_rGTue-
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/bank_marketing.ipynb
100% 299k/299k [00:00<00:00, 96.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=10K-o2kY9j6kt2X8-TT4tbKtSuZrYGd7s
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/bank-additional-full.csv
100% 5.26M/5.26M [00:00<00:00, 23.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pnuFvs5E2aLB_xDLg9jxlHn8a-xnIpU3
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/categories_ohe.pickle
100% 691/691 [00:00<00:00, 2.66MB/s]
Downloading...
From: https://drive.google.com/uc?id=159gW5RPsN_PYfrJZjtw3qo32WNwyQauI
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/limpieza_datos_nulos.pickle
100% 3.84M/3.84M [00:00<00:00, 47.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NSJ0KFhOtjMTE0WHjlSlwVB-_EIZcDB2
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/tarea_respuesta1.csv
100% 1.21k/1.21k [00:00<00:00, 4.71MB/s]
Downloading...
From: https://drive.google.com/uc?id=1rFPxoS4mTjn0zWa0oleGLzhd_KUwWqSN
To: /content/Bootcamp Data Science-Grupo 1/tp4/Archivos_del_martes/tarea_respuesta2.csv
100% 8.75k/8.75k [00:00<00:00, 32.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=17AFvwGkPL7midocDg40OIP-ZVt1Hjsek
To: /content/Bootcamp Data Science-Grupo 1/2_9.ipynb
100% 118k/118k [00:00<00:00, 81.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1K_4B0oQIDThK4U2rUUoDCPXGqzEKTUZz
To: /content/Bootcamp Data Science-Grupo 1/archive.zip
100% 240k/240k [00:00<00:00, 90.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=18TvelehEBbcPf9qP69QAdrr8mLcwIBlK
To: /content/Bootcamp Data Science-Grupo 1/dataset_phishing.csv
100% 3.66M/3.66M [00:00<00:00, 162MB/s]
Downloading...
From: https://drive.google.com/uc?id=1AqNP3cV9Hzn0JaB9xMh8C68LXgXwUbmg
To: /content/Bootcamp Data Science-Grupo 1/IntroPhyton.ipynb
100% 49.5k/49.5k [00:00<00:00, 85.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1d_HHaVCs0gn0Oiyn9_CKJQEMwNtJ3Noo
To: /content/Bootcamp Data Science-Grupo 1/Phishing_Legitimate_full.csv
100% 1.41M/1.41M [00:00<00:00, 156MB/s]
Download completed

In [ ]:
!gdown --id 1IWVNIVT1feXTfBDq2S9CdWeIrGN7AUj1 -O encuesta-anual-hogares-2019.csv

data = pd.read_csv("encuesta-anual-hogares-2019.csv", sep=',')

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1IWVNIVT1feXTfBDq2S9CdWeIrGN7AUj1
To: /content/encuesta-anual-hogares-2019.csv
100% 5.17M/5.17M [00:00<00:00, 96.6MB/s]

In [ ]:
data

,id,nhogar,miembro,comuna,dominio,edad,sexo,parentesco_jefe,situacion_conyugal,num_miembro_padre,...,ingreso_per_capita_familiar,estado_educativo,sector_educativo,nivel_actual,nivel_max_educativo,años_escolaridad,lugar_nacimiento,afiliacion_salud,hijos_nacidos_vivos,cantidad_hijos_nac_vivos
0,1,1,1,5,Resto de la Ciudad,18,Mujer,Jefe,Soltero/a,Padre no vive en el hogar,...,9000,Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,PBA excepto GBA,Solo obra social,No,No corresponde
1,1,1,2,5,Resto de la Ciudad,18,Mujer,Otro no familiar,Soltero/a,Padre no vive en el hogar,...,9000,Asiste,Estatal/publico,Universitario,Otras escuelas especiales,12,Otra provincia,Solo plan de medicina prepaga por contratación...,No,No corresponde
2,2,1,1,2,Resto de la Ciudad,18,Varon,Jefe,Soltero/a,Padre no vive en el hogar,...,33333,Asiste,Privado religioso,Universitario,Otras escuelas especiales,12,CABA,Solo plan de medicina prepaga por contratación...,NaN,No corresponde
3,2,1,2,2,Resto de la Ciudad,50,Mujer,Padre/Madre/Suegro/a,Viudo/a,No corresponde,...,33333,No asiste pero asistió,No corresponde,No corresponde,Secundario/medio comun,17,CABA,Solo prepaga o mutual via OS,Si,2
4,2,1,3,2,Resto de la Ciudad,17,Varon,Otro familiar,Soltero/a,Padre no vive en el hogar,...,33333,Asiste,Privado religioso,Secundario/medio comun,EGB (1° a 9° año),10,CABA,Solo plan de medicina prepaga por contratación...,NaN,No corresponde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14314,5794,1,1,10,Resto de la Ciudad,99,Varon,Jefe,Casado/a,No corresponde,...,14250,No asiste pero asistió,No corresponde,No corresponde,Sala de 5,5,Pais no limitrofe,Solo obra social,NaN,No corresponde
14315,5794,1,2,10,Resto de la Ciudad,78,Mujer,Otro familiar,Soltero/a,No corresponde,...,14250,No asiste pero asistió,No corresponde,No corresponde,EGB (1° a 9° año),9,Partido GBA,Solo obra social,No,No corresponde
14316,5794,1,3,10,Resto de la Ciudad,60,Mujer,Hijo/a - Hijastro/a,Separado/a de unión o matrimonio,No corresponde,...,14250,No asiste pero asistió,No corresponde,No corresponde,Primario especial,12,CABA,Solo obra social,Si,2
14317,5794,1,4,10,Resto de la Ciudad,92,Mujer,Conyugue o pareja,Casado/a,No corresponde,...,14250,No asiste pero asistió,No corresponde,No corresponde,Primario comun,7,CABA,Solo obra social,Si,1
14318,5795,1,1,2,Resto de la Ciudad,100,Mujer,Jefe,Viudo/a,No corresponde,...,82000,No asiste pero asistió,No corresponde,No corresponde,Secundario/medio comun,15,CABA,Solo obra social,Si,1

## 2) Inspección inicial

In [ ]:
# Eliminamos las columnas id y hijos_nacidos_vivos
data = data.drop(columns=['id', 'hijos_nacidos_vivos'])

In [ ]:
status(data)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,nhogar,0,0.000000,0,0.000000,7,int64
1,miembro,0,0.000000,0,0.000000,19,int64
2,comuna,0,0.000000,0,0.000000,15,int64
3,dominio,0,0.000000,0,0.000000,2,object
4,edad,0,0.000000,128,0.008939,101,int64
5,sexo,0,0.000000,0,0.000000,2,object
6,parentesco_jefe,0,0.000000,0,0.000000,9,object
7,situacion_conyugal,1,0.000070,0,0.000000,7,object
8,num_miembro_padre,0,0.000000,0,0.000000,9,object
9,num_miembro_madre,0,0.000000,0,0.000000,11,object
10,estado_ocupacional,0,0.000000,0,0.000000,3,object
11,cat_ocupacional,0,0.000000,0,0.000000,5,object
12,calidad_ingresos_lab,0,0.000000,0,0.000000,4,object
13,ingreso_total_lab,0,0.000000,6963,0.486277,440,int64
14,calidad_ingresos_no_lab,0,0.000000,0,0.000000,4,object
15,ingreso_total_no_lab,0,0.000000,10247,0.715623,375,int64
16,calidad_ingresos_totales,0,0.000000,0,0.000000,4,object
17,ingresos_totales,0,0.000000,4295,0.299951,678,int64
18,calidad_ingresos_familiares,0,0.000000,0,0.000000,3,object
19,ingresos_familiares,0,0.000000,76,0.005308,960,int64
20,ingreso_per_capita_familiar,0,0.000000,76,0.005308,1257,int64
21,estado_educativo,0,0.000000,0,0.000000,3,object
22,sector_educativo,3,0.000210,0,0.000000,4,object
23,nivel_actual,0,0.000000,0,0.000000,14,object
24,nivel_max_educativo,1054,0.073608,0,0.000000,7,object
25,años_escolaridad,62,0.004330,0,0.000000,20,object
26,lugar_nacimiento,1,0.000070,0,0.000000,7,object
27,afiliacion_salud,4,0.000279,0,0.000000,5,object
28,cantidad_hijos_nac_vivos,0,0.000000,0,0.000000,14,object

## 3) Discretización
- Para las siguientes columnas discreticen por igual frecuencia e igual rango.
    <br>`ingresos_familiares` con q=8
    <br>`ingreso_per_capita_familiar` con q=10

In [ ]:
data2=data.copy()

In [ ]:
data2['ingresos_familiares']=pd.qcut(data2['ingresos_familiares'], q=8)
data2['ingreso_per_capita_familiar']=pd.qcut(data2['ingreso_per_capita_familiar'], q=10)

In [ ]:
data2[['ingresos_familiares','ingreso_per_capita_familiar']]

       ingresos_familiares ingreso_per_capita_familiar
0        (-0.001, 20800.0]           (8700.0, 12000.0]
1        (-0.001, 20800.0]           (8700.0, 12000.0]
2      (90000.0, 124000.0]          (30000.0, 38300.0]
3      (90000.0, 124000.0]          (30000.0, 38300.0]
4      (90000.0, 124000.0]          (30000.0, 38300.0]
...                    ...                         ...
14314   (54000.0, 70000.0]          (12000.0, 15016.0]
14315   (54000.0, 70000.0]          (12000.0, 15016.0]
14316   (54000.0, 70000.0]          (12000.0, 15016.0]
14317   (54000.0, 70000.0]          (12000.0, 15016.0]
14318   (70000.0, 90000.0]        (52340.0, 1000000.0]

[14319 rows x 2 columns]

- En algunas situaciones hay ciertos elementos que se repiten al momento de discretizar, una forma de eliminar duplicados es con el argumento `duplicates='drop'`.
    <br><br>Para las siguientes columnas `ingreso_total_lab` y `ingreso_total_no_lab` consideren:

In [ ]:
data2['ingreso_total_lab'] = pd.qcut(data2['ingreso_total_lab'], q=10, duplicates='drop')
data2['ingreso_total_no_lab'] = pd.qcut(data['ingreso_total_no_lab'], q=4, duplicates='drop')

In [ ]:
data2[['ingreso_total_lab','ingreso_total_no_lab']]

          ingreso_total_lab ingreso_total_no_lab
0          (-0.001, 2500.0]   (4000.0, 500000.0]
1          (-0.001, 2500.0]   (4000.0, 500000.0]
2          (-0.001, 2500.0]     (-0.001, 4000.0]
3      (56000.0, 1000000.0]   (4000.0, 500000.0]
4          (-0.001, 2500.0]     (-0.001, 4000.0]
...                     ...                  ...
14314      (-0.001, 2500.0]   (4000.0, 500000.0]
14315      (-0.001, 2500.0]   (4000.0, 500000.0]
14316      (-0.001, 2500.0]   (4000.0, 500000.0]
14317      (-0.001, 2500.0]   (4000.0, 500000.0]
14318      (-0.001, 2500.0]   (4000.0, 500000.0]

[14319 rows x 2 columns]

- Para la columna `edad` discreticen usando igual distancia con `bins=5`.

In [ ]:
data2['edad']=pd.cut(data2['edad'],bins=5)

In [ ]:
data2['edad']

0         (-0.1, 20.0]
1         (-0.1, 20.0]
2         (-0.1, 20.0]
3         (40.0, 60.0]
4         (-0.1, 20.0]
             ...
14314    (80.0, 100.0]
14315     (60.0, 80.0]
14316     (40.0, 60.0]
14317    (80.0, 100.0]
14318    (80.0, 100.0]
Name: edad, Length: 14319, dtype: category
Categories (5, interval[float64, right]): [(-0.1, 20.0] < (20.0, 40.0] < (40.0, 60.0] <
                                           (60.0, 80.0] < (80.0, 100.0]]

## 4) Preparación de datos

- Cambien el tipo de dato a `str` de las siguientes columnas: `comuna` y `nhogar`.
  <br>_¿Por qué hacemos esto?_ Para estas columnas el número es simplemente una connotación, para representar una comuna por ejemplo pero no hay una relación numérica entre ellos.

In [ ]:
status(data2)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,nhogar,0,0.000000,0,0.000000,7,int64
1,miembro,0,0.000000,0,0.000000,19,int64
2,comuna,0,0.000000,0,0.000000,15,int64
3,dominio,0,0.000000,0,0.000000,2,object
4,edad,0,0.000000,0,0.000000,5,category
5,sexo,0,0.000000,0,0.000000,2,object
6,parentesco_jefe,0,0.000000,0,0.000000,9,object
7,situacion_conyugal,1,0.000070,0,0.000000,7,object
8,num_miembro_padre,0,0.000000,0,0.000000,9,object
9,num_miembro_madre,0,0.000000,0,0.000000,11,object
10,estado_ocupacional,0,0.000000,0,0.000000,3,object
11,cat_ocupacional,0,0.000000,0,0.000000,5,object
12,calidad_ingresos_lab,0,0.000000,0,0.000000,4,object
13,ingreso_total_lab,0,0.000000,0,0.000000,6,category
14,calidad_ingresos_no_lab,0,0.000000,0,0.000000,4,object
15,ingreso_total_no_lab,0,0.000000,0,0.000000,2,category
16,calidad_ingresos_totales,0,0.000000,0,0.000000,4,object
17,ingresos_totales,0,0.000000,4295,0.299951,678,int64
18,calidad_ingresos_familiares,0,0.000000,0,0.000000,3,object
19,ingresos_familiares,0,0.000000,0,0.000000,8,category
20,ingreso_per_capita_familiar,0,0.000000,0,0.000000,10,category
21,estado_educativo,0,0.000000,0,0.000000,3,object
22,sector_educativo,3,0.000210,0,0.000000,4,object
23,nivel_actual,0,0.000000,0,0.000000,14,object
24,nivel_max_educativo,1054,0.073608,0,0.000000,7,object
25,años_escolaridad,62,0.004330,0,0.000000,20,object
26,lugar_nacimiento,1,0.000070,0,0.000000,7,object
27,afiliacion_salud,4,0.000279,0,0.000000,5,object
28,cantidad_hijos_nac_vivos,0,0.000000,0,0.000000,14,object

In [ ]:
data2['comuna'] = data2['comuna'].astype(str)
data2['nhogar'] = data2['nhogar'].astype(str)

In [ ]:
status(data2)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,nhogar,0,0.000000,0,0.000000,7,object
1,miembro,0,0.000000,0,0.000000,19,int64
2,comuna,0,0.000000,0,0.000000,15,object
3,dominio,0,0.000000,0,0.000000,2,object
4,edad,0,0.000000,0,0.000000,5,category
5,sexo,0,0.000000,0,0.000000,2,object
6,parentesco_jefe,0,0.000000,0,0.000000,9,object
7,situacion_conyugal,1,0.000070,0,0.000000,7,object
8,num_miembro_padre,0,0.000000,0,0.000000,9,object
9,num_miembro_madre,0,0.000000,0,0.000000,11,object
10,estado_ocupacional,0,0.000000,0,0.000000,3,object
11,cat_ocupacional,0,0.000000,0,0.000000,5,object
12,calidad_ingresos_lab,0,0.000000,0,0.000000,4,object
13,ingreso_total_lab,0,0.000000,0,0.000000,6,category
14,calidad_ingresos_no_lab,0,0.000000,0,0.000000,4,object
15,ingreso_total_no_lab,0,0.000000,0,0.000000,2,category
16,calidad_ingresos_totales,0,0.000000,0,0.000000,4,object
17,ingresos_totales,0,0.000000,4295,0.299951,678,int64
18,calidad_ingresos_familiares,0,0.000000,0,0.000000,3,object
19,ingresos_familiares,0,0.000000,0,0.000000,8,category
20,ingreso_per_capita_familiar,0,0.000000,0,0.000000,10,category
21,estado_educativo,0,0.000000,0,0.000000,3,object
22,sector_educativo,3,0.000210,0,0.000000,4,object
23,nivel_actual,0,0.000000,0,0.000000,14,object
24,nivel_max_educativo,1054,0.073608,0,0.000000,7,object
25,años_escolaridad,62,0.004330,0,0.000000,20,object
26,lugar_nacimiento,1,0.000070,0,0.000000,7,object
27,afiliacion_salud,4,0.000279,0,0.000000,5,object
28,cantidad_hijos_nac_vivos,0,0.000000,0,0.000000,14,object

- _¿Qué esperas como valor en la columna `años_escolaridad`?_ Número enteros pero no siempre es así, cada entidad o empresa tiene diferentes formas de rellenar una encuesta.
    <br>Evalua lo siguiente: `data['años_escolaridad'].unique()`, vas a poder ver los valores únicos en la columna. Donde destacamos que todos son `object/string`.

In [ ]:
data2['años_escolaridad'].unique()

array(['12', '17', '10', '8', 'Ningun año de escolaridad aprobado', '11',
       '9', '13', '7', '16', '14', '15', '5', '6', '2', '19', '4', '1',
       '3', '18', nan], dtype=object)

- Reemplazar `Ningun año de escolaridad aprobado` por un '0'.
<br>Efectivamente por '0' y no 0, porque esta columna maneja datos tipo `object/string`.
    ```
    data['años_escolaridad'] = data['años_escolaridad'].replace('Ningun año de escolaridad aprobado', '0')
    ```

In [ ]:
data2['años_escolaridad'] = data2['años_escolaridad'].replace('Ningun año de escolaridad aprobado', '0')

- Vamos a convertir los tipos de datos de la columna anterior `años_escolaridad` a enteros.
    <br>De manera intuitiva podríamos hacer:
    ```
    data['años_escolaridad'] = data['años_escolaridad'].astype("Int32")
    ```
    PEROOOOOOO marca un error, ¿cierto?
    
    Posiblemente muchas veces les pase que cuando hagan una _cast_ (conversión de un tipo de dato a otro) pueden llegar a tener conflictos si esa columna tienen _NaN_. Para este caso si queremos convertir los valores de la columna `años_escolaridad` de _string_ a _int_, hay que hacer un paso intermedio que es pasarlo a _float_.
    ```
    data['años_escolaridad'] = data['años_escolaridad'].astype(float).astype("Int32")
    ```

In [ ]:
data2['años_escolaridad'] = data2['años_escolaridad'].astype("Int32")

In [ ]:
data2['años_escolaridad'].unique()

<IntegerArray>
[12, 17, 10, 8, 0, 11, 9, 13, 7, 16, 14, 15, 5, 6, 2, 19, 4, 1, 3, 18, <NA>]
Length: 21, dtype: Int32

- Discreticen para la columna `años_escolaridad` por igual frecuencia e igual rango con un `q=5`

In [ ]:
data2['años_escolaridad']=pd.qcut(data2['años_escolaridad'], q=5)

- No necesariamente siempre hay que rellenar los `NaN` en todas las columnas, porque quizás esa cantidad de `NaN` no es tan representativa para nuestro análisis. Así que podes eliminarlo para todo el dataframe o para ciertas columnas.
    ```
    # Eliminar filas que contengan NaN
    data = data.dropna(subset=['situacion_conyugal', 'sector_educativo', 'lugar_nacimiento', 'afiliacion_salud'])
    ```

In [ ]:
# Eliminar filas que contengan NaN
data2 = data2.dropna(subset=['situacion_conyugal', 'sector_educativo', 'lugar_nacimiento', 'afiliacion_salud'])

- Después de eliminar filas, podes resetear el índice para que mantenga la secuencia:
    ```
    data = data.reset_index(drop=True)
    ```

In [ ]:
data2 = data2.reset_index(drop=True)

- Rellenar los datos faltantes para la columna `años_escolaridad`. Primero añadan la categoría `desconocido` y luego hacen un rellenado de los datos faltantes con `desconocido`.

In [ ]:
data2['años_escolaridad'] = (
    data2['años_escolaridad']
    .astype('category')
    .cat.add_categories(['desconocido'])
    .fillna('desconocido')
)

- Rellenar los datos faltantes para la columna `nivel_max_educativo` con `value=desconocido`

In [ ]:
data2['nivel_max_educativo']=data2['nivel_max_educativo'].fillna(value="desconocido")

##Comparación con Respuesta Esperada 1

In [ ]:
status(data2)

,variable,q_nan,p_nan,q_zeros,p_zeros,unique,type
0,nhogar,0,0.0,0,0.00000,7,object
1,miembro,0,0.0,0,0.00000,19,int64
2,comuna,0,0.0,0,0.00000,15,object
3,dominio,0,0.0,0,0.00000,2,object
4,edad,0,0.0,0,0.00000,5,category
5,sexo,0,0.0,0,0.00000,2,object
6,parentesco_jefe,0,0.0,0,0.00000,9,object
7,situacion_conyugal,0,0.0,0,0.00000,7,object
8,num_miembro_padre,0,0.0,0,0.00000,9,object
9,num_miembro_madre,0,0.0,0,0.00000,11,object
10,estado_ocupacional,0,0.0,0,0.00000,3,object
11,cat_ocupacional,0,0.0,0,0.00000,5,object
12,calidad_ingresos_lab,0,0.0,0,0.00000,4,object
13,ingreso_total_lab,0,0.0,0,0.00000,6,category
14,calidad_ingresos_no_lab,0,0.0,0,0.00000,4,object
15,ingreso_total_no_lab,0,0.0,0,0.00000,2,category
16,calidad_ingresos_totales,0,0.0,0,0.00000,4,object
17,ingresos_totales,0,0.0,4290,0.29979,678,int64
18,calidad_ingresos_familiares,0,0.0,0,0.00000,3,object
19,ingresos_familiares,0,0.0,0,0.00000,8,category
20,ingreso_per_capita_familiar,0,0.0,0,0.00000,10,category
21,estado_educativo,0,0.0,0,0.00000,3,object
22,sector_educativo,0,0.0,0,0.00000,4,object
23,nivel_actual,0,0.0,0,0.00000,14,object
24,nivel_max_educativo,0,0.0,0,0.00000,8,object
25,años_escolaridad,0,0.0,0,0.00000,6,category
26,lugar_nacimiento,0,0.0,0,0.00000,7,object
27,afiliacion_salud,0,0.0,0,0.00000,5,object
28,cantidad_hijos_nac_vivos,0,0.0,0,0.00000,14,object

## 📍 Consigna 2

**_5) One hot encoding_**

- Hagan `data_ohe = pd.get_dummies(data)`

In [ ]:
data_ohe = pd.get_dummies(data2)

In [ ]:
data_ohe.head()

,miembro,ingresos_totales,nhogar_1,nhogar_2,nhogar_3,nhogar_4,nhogar_5,nhogar_6,nhogar_7,comuna_1,...,cantidad_hijos_nac_vivos_15,cantidad_hijos_nac_vivos_2,cantidad_hijos_nac_vivos_3,cantidad_hijos_nac_vivos_4,cantidad_hijos_nac_vivos_5,cantidad_hijos_nac_vivos_6,cantidad_hijos_nac_vivos_7,cantidad_hijos_nac_vivos_8,cantidad_hijos_nac_vivos_9,cantidad_hijos_nac_vivos_No corresponde
0,1,6000,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
1,2,12000,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,1,0,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,2,100000,True,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
4,3,0,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [ ]:
data_ohe.columns

Index(['miembro', 'ingresos_totales', 'nhogar_1', 'nhogar_2', 'nhogar_3',
       'nhogar_4', 'nhogar_5', 'nhogar_6', 'nhogar_7', 'comuna_1',
       ...
       'cantidad_hijos_nac_vivos_15', 'cantidad_hijos_nac_vivos_2',
       'cantidad_hijos_nac_vivos_3', 'cantidad_hijos_nac_vivos_4',
       'cantidad_hijos_nac_vivos_5', 'cantidad_hijos_nac_vivos_6',
       'cantidad_hijos_nac_vivos_7', 'cantidad_hijos_nac_vivos_8',
       'cantidad_hijos_nac_vivos_9',
       'cantidad_hijos_nac_vivos_No corresponde'],
      dtype='object', length=179)

- Guardar `data_ohe` en un archivo pickle como vimos en clase con el nombre `categories_ohe.pickle`.

In [ ]:
import pickle

with open('categories_ohe.pickle', 'wb') as handle:
    pickle.dump(data_ohe.columns, handle, protocol=pickle.HIGHEST_PROTOCOL)

- Carguen el dataset `new_data = pd.read_csv("new_data.csv", sep=',')`

In [ ]:
!gdown --id 1rJcEV0YP-nTRmxziBB9417F-dIKdFCl2 -O new_data.csv
new_data= pd.read_csv("new_data.csv", sep=',')

/usr/local/lib/python3.12/dist-packages/gdown/__main__.py:140: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1rJcEV0YP-nTRmxziBB9417F-dIKdFCl2
To: /content/new_data.csv
100% 2.57k/2.57k [00:00<00:00, 8.53MB/s]

- A `new_data` hagan un reindex con las columnas que guardaron el archivo pickle y para los valores `NaN` rellenenlos con un `0`.

In [ ]:
with open('categories_ohe.pickle', 'rb') as handle:
    ohe_tr = pickle.load(handle)

In [ ]:
ohe_tr

Index(['miembro', 'ingresos_totales', 'nhogar_1', 'nhogar_2', 'nhogar_3',
       'nhogar_4', 'nhogar_5', 'nhogar_6', 'nhogar_7', 'comuna_1',
       ...
       'cantidad_hijos_nac_vivos_15', 'cantidad_hijos_nac_vivos_2',
       'cantidad_hijos_nac_vivos_3', 'cantidad_hijos_nac_vivos_4',
       'cantidad_hijos_nac_vivos_5', 'cantidad_hijos_nac_vivos_6',
       'cantidad_hijos_nac_vivos_7', 'cantidad_hijos_nac_vivos_8',
       'cantidad_hijos_nac_vivos_9',
       'cantidad_hijos_nac_vivos_No corresponde'],
      dtype='object', length=179)

In [ ]:
d_tr_ohe_2 = pd.get_dummies(new_data).reindex(columns = ohe_tr).fillna("0")

##Comparación Respuesta Esperada 2

In [ ]:
d_tr_ohe_2

,miembro,ingresos_totales,nhogar_1,nhogar_2,nhogar_3,nhogar_4,nhogar_5,nhogar_6,nhogar_7,comuna_1,...,cantidad_hijos_nac_vivos_15,cantidad_hijos_nac_vivos_2,cantidad_hijos_nac_vivos_3,cantidad_hijos_nac_vivos_4,cantidad_hijos_nac_vivos_5,cantidad_hijos_nac_vivos_6,cantidad_hijos_nac_vivos_7,cantidad_hijos_nac_vivos_8,cantidad_hijos_nac_vivos_9,cantidad_hijos_nac_vivos_No corresponde
0,1,4000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
1,1,22000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
2,1,25000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
3,2,30000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True
4,1,20000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,True

## 📍 Consigna 3

Cargar su notebook y datasets a un repositorio público personal y compartirlo por Discord.
<br>Consideren usar git lfs para los dataset con extensión csv.